server:
  port: 8084
  servlet:
    context-path: /std

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  main:
    allow-circular-references: true

  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://10.10.250.242:3306/ojtdb?charSet=UTF-8
    username: letech
    password: Dpfdlxpzm08!

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: kr.letech.study.dto
  
logging:
  level:
    jdbc: warn
    sqlonly: debug
    com:
      prototype:
        domain:
          repository: TRACE
    org:
      springframework:
        web : info
      hibernate:
        SQL: off
    sql: debug
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"

custom:
  path:
    file: "D:/resources/files"
    summernote: "D:/resources/summernoteImage"
    thumbnail: "/summernoteImage"

    
    